apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 853173989967.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 853173989967.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: 144431aa
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
